- name: start aws config recordings 
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - aws_keys.yml

  tasks:
      - name: Create Configuration Recorder for AWS Config
        aws_config_recorder:
          name: test_configuration_recorder
          region: us-east-1
          state: present
          # wait: True
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          role_arn: 'config_role'
          recording_group:
              all_supported: true
              include_global_types: true